# Generated by Django 4.0.1 on 2022-01-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(choices=[('supplier', 'Supplier'), ('customer', 'Customer')], default='customer', max_length=10, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
