# Generated by Django 4.0.2 on 2022-03-09 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
        ('invoice', '0010_alter_invoice_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, null=True)),
                ('date', models.DateField(null=True)),
                ('type', models.CharField(choices=[('pay', 'Pay'), ('receipt', 'Receipt')], default='', max_length=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='draft', max_length=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_partner', to='partner.partner')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pay', 'Pay'), ('receipt', 'Receipt')], default='', max_length=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='draft', max_length=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('allocated', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('outstanding', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_line_invo', to='invoice.invoice')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_line_parant', to='payment.payment')),
            ],
        ),
    ]
