# Generated by Django 4.0.1 on 2022-01-18 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
        ('invoice', '0003_invoice_date_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='partner.partner'),
        ),
    ]
