# Generated by Django 4.0.2 on 2022-02-23 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_status_alter_invoice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='invoice.invoice'),
        ),
    ]
