# Generated by Django 4.0.2 on 2022-02-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_remove_invoiceline_invoice_invoiceline_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='draft', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
