# Generated by Django 4.0.2 on 2022-03-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_invoice_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payments',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
