# Generated by Django 4.0 on 2022-01-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(choices=[('stock', 'Stockable'), ('service', 'Service')], default='stock', max_length=10, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('purchase', models.FloatField(default=0.0)),
                ('descrip', models.CharField(max_length=120)),
                ('qty', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
