# Generated by Django 4.0.2 on 2022-03-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_cost_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('stockable', 'Stockable'), ('service', 'Service')], default='stockable', max_length=10, null=True),
        ),
    ]
