# Generated by Django 4.0.2 on 2022-02-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_namingseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namingseries',
            name='fill',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='namingseries',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
