# Generated by Django 4.0.2 on 2022-02-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentryline',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='draft', max_length=10, null=True),
        ),
    ]
