# Generated by Django 4.0.2 on 2022-03-02 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_purchase_product_cost'),
        ('invoice', '0008_remove_invoiceline_product_invoice_outstanding_and_more'),
        ('stock', '0003_alter_stockentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ste_parent', to='invoice.invoice'),
        ),
        migrations.AddField(
            model_name='stockentryline',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockentryline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='str_line_item', to='product.product'),
        ),
        migrations.AlterField(
            model_name='stockentryline',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ste_line_parent', to='stock.stockentry'),
        ),
        migrations.AlterField(
            model_name='stockentryline',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockentryline',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
