# Generated by Django 4.0.2 on 2022-02-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stockentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentryline',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
