# Generated by Django 4.0.2 on 2022-03-02 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockentry_parent_stockentryline_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentryline',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ste_line_parent', to='stock.stockentry'),
        ),
    ]
