# Generated by Django 4.0.2 on 2022-03-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stockentryline_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentryline',
            name='qty_stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
