# Generated by Django 4.0.2 on 2022-03-07 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stockentryline_qty_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentryline',
            name='qty_stock',
        ),
    ]
