# Generated by Django 4.0.2 on 2022-03-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_invoiceline_qty_stock'),
        ('product', '0004_alter_product_type'),
        ('stock', '0007_remove_stockentryline_qty_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentryline',
            name='inv_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invo_line_parent', to='invoice.invoiceline'),
        ),
        migrations.AlterField(
            model_name='stockentryline',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='str_line_item', to='product.product'),
        ),
        migrations.AlterField(
            model_name='stockentryline',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ste_line_parent', to='stock.stockentry'),
        ),
    ]
