# Generated by Django 4.0.2 on 2022-03-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_stockentryline_inv_line_alter_stockentryline_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockentryline',
            old_name='inv_line',
            new_name='invo_line',
        ),
    ]
