# Generated by Django 4.0.2 on 2022-03-08 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_invoice_code'),
        ('stock', '0009_rename_inv_line_stockentryline_invo_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentryline',
            name='invo_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invo_line_parent', to='invoice.invoiceline'),
        ),
    ]
